import { useEffect, useRef, useState } from "react";
import { Terminal } from "lucide-react";
import type { RunnerState } from "@/hooks/useCodeRunner";
import WarehouseMetrics from "../../components/warehouse/WarehouseMetrics";

interface ArenaSidebarProps {
    runnerState: RunnerState;
}

export default function ArenaSidebar({ runnerState }: ArenaSidebarProps) {
    // Console auto-scroll controls:
    // - `consoleRef` points to the scrollable console DOM node.
    // - `endRef` is a sentinel element used for reliable scrollIntoView.
    // - `isProgrammaticScrollRef` is used to ignore scroll events generated by our own scrolling code.
    // - `autoScroll` keeps the view pinned to the bottom unless the user scrolls up.
    // - `userScrolledUp` is used to show a jump-to-latest control.
    const consoleRef = useRef<HTMLDivElement | null>(null);
    const endRef = useRef<HTMLDivElement | null>(null);
    const isProgrammaticScrollRef = useRef(false);
    const [autoScroll, setAutoScroll] = useState(true);
    const [userScrolledUp, setUserScrolledUp] = useState(false);

    // When the output changes, if autoScroll is enabled keep the console pinned to bottom.
    // Scroll to bottom when output changes, prefer using an end sentinel to avoid layout jitter.
    useEffect(() => {
        const el = consoleRef.current;
        if (!el) return;
        if (autoScroll) {
            // mark that we are performing a programmatic scroll so onScroll handlers can ignore resulting events
            isProgrammaticScrollRef.current = true;
            // schedule after render so content is present
            requestAnimationFrame(() => {
                const end = endRef.current;
                if (end && typeof end.scrollIntoView === "function") {
                    // Use scrollIntoView on the sentinel so dynamic layout changes behave correctly
                    end.scrollIntoView({ block: "end", behavior: "auto" });
                } else {
                    // fallback to direct scrollTop manipulation
                    el.scrollTop = el.scrollHeight;
                }
                // After the programmatic scroll completes, clear the flag on the next frame
                // so subsequent user interactions are detected.
                requestAnimationFrame(() => {
                    isProgrammaticScrollRef.current = false;
                });
            });
        }
    }, [runnerState.output.length, runnerState.error, autoScroll]);

    return (
        <div className="w-1/3 max-w-160 flex-1 flex flex-col bg-zinc-950 shrink-0 lg:flex border-l border-zinc-800 h-full overflow-hidden">
            {/* Sidebar Header */}
            <div className="p-3 border-b border-zinc-800 flex items-center justify-between bg-zinc-900 shrink-0">
                <div className="flex items-center gap-2">
                    <Terminal size={16} className="text-zinc-500" />
                    <h3 className="text-xs font-medium text-zinc-400 uppercase tracking-wider font-sans">
                        Local Execution Floor
                    </h3>
                </div>
                <div className="text-[10px] font-bold text-zinc-500 uppercase font-sans">
                    {runnerState.status}
                </div>
            </div>

            {/* Content Area */}
            <div className="flex-1 p-4 flex flex-col text-zinc-500 min-h-0">
                {/* Metric Cards */}
                <WarehouseMetrics
                    events={
                        runnerState.warehouseEvents as unknown as import("@/components/warehouse/types").WarehouseEventPayload[]
                    }
                    runnerStatus={runnerState.status}
                />

                {/* Console Output Pane */}
                <div className="w-full mt-4 flex-1 flex flex-col bg-zinc-900 rounded-md border border-zinc-800 overflow-hidden min-h-0">
                    <div className="bg-zinc-800/50 p-2 text-[10px] font-mono text-zinc-500 uppercase border-b border-zinc-800 shrink-0">
                        Console Output
                    </div>
                    <div className="relative flex-1 overflow-hidden flex flex-col">
                        {/* scrollable console area */}
                        <div
                            ref={consoleRef}
                            tabIndex={0}
                            role="log"
                            aria-live="polite"
                            onScroll={(e) => {
                                // Ignore scroll events generated by our own programmatic scrolling.
                                if (isProgrammaticScrollRef.current) return;
                                const el = e.currentTarget as HTMLDivElement;
                                // distance from bottom
                                const distanceFromBottom =
                                    el.scrollHeight -
                                    (el.scrollTop + el.clientHeight);
                                const atBottom = distanceFromBottom < 24;
                                setAutoScroll(atBottom);
                                setUserScrolledUp(!atBottom);
                            }}
                            style={{ height: "100%", overflowY: "auto" }}
                            className="p-3 text-xs font-mono text-zinc-300 whitespace-pre-wrap text-left w-full flex-1 flex flex-col gap-1 scrollbar-thin scrollbar-thumb-zinc-700"
                        >
                            {runnerState.output.length === 0 &&
                            !runnerState.error ? (
                                <pre className="text-zinc-600 italic p-0 m-0">
                                    No output...
                                </pre>
                            ) : (
                                <div className="flex flex-col gap-0">
                                    {runnerState.output.map((line, i) => (
                                        <pre
                                            key={i}
                                            className={`whitespace-pre-wrap p-0 m-0 ${
                                                line.startsWith("ERROR:")
                                                    ? "text-rose-400 font-bold"
                                                    : "text-zinc-300"
                                            }`}
                                        >
                                            {line}
                                        </pre>
                                    ))}
                                    {runnerState.error && (
                                        <pre className="whitespace-pre-wrap p-0 m-0 text-rose-500 font-bold">
                                            {runnerState.error}
                                        </pre>
                                    )}
                                </div>
                            )}
                            {/* sentinel element used by scrollIntoView to reliably pin to the end */}
                            <div ref={endRef} />
                        </div>

                        {/* Jump-to-latest button (shows when user scrolled up) */}
                        {userScrolledUp && (
                            <div className="absolute right-3 bottom-3">
                                <button
                                    onClick={() => {
                                        setAutoScroll(true);
                                        // mark that we're doing a programmatic scroll so onScroll ignores the resulting event
                                        isProgrammaticScrollRef.current = true;
                                        const el = consoleRef.current;
                                        if (el) {
                                            el.scrollTop = el.scrollHeight;
                                        }
                                        // clear programmatic flag shortly after scrolling completes
                                        setTimeout(() => {
                                            isProgrammaticScrollRef.current = false;
                                        }, 120);
                                    }}
                                    className="bg-zinc-800/80 text-zinc-200 px-2 py-1 rounded text-xs border border-zinc-700 hover:bg-zinc-700/90"
                                >
                                    Jump to latest
                                </button>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
}
